


% -DTIMING_TEST

if(isunix)
  if(strcmp(computer, 'GLNX86'))
    mex -v -O -DTIXML_USE_TICPP ...
        -I../../include/  -I../../extern/include/  ...
        -lboost_thread -lboost_system -lstdc++...
        -outdir build ...
        src/mex_get_config.cpp    ...
        ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
        ../../src/definitions/constants.cpp ../../src/config/control_message_encoder.cpp ...
        ../../src/config/control_messages.cpp ../../src/config/control_message_decoder.cpp ...
        ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
        ../../extern/lib/ticpp/linux/libticpp.a


    mex -v -O -DTIXML_USE_TICPP ...
        -I../../include/  -I../../extern/include/  ...
        -lboost_thread -lboost_system -lstdc++...
        -outdir build ...
        src/simulink_get_data.cpp ...
        ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
        ../../src/definitions/constants.cpp ../../src/config/control_message_decoder.cpp ...
        ../../src/config/control_messages.cpp ../../src/config/control_message_encoder.cpp ...
        ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
        ../../extern/lib/ticpp/linux/libticpp.a
  else
    mex -v -O -DTIXML_USE_TICPP ...
        -I../../include/  -I../../extern/include/  ...
        -lboost_thread -lboost_system -lstdc++...
        -outdir build ...
        src/mex_get_config.cpp    ...
        ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
        ../../src/definitions/constants.cpp ../../src/config/control_message_encoder.cpp ...
        ../../src/config/control_messages.cpp ../../src/config/control_message_decoder.cpp ...
        ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
        ../../extern/lib/ticpp/linux/libticpp_64.a


    mex -v -O -DTIXML_USE_TICPP ...
        -I../../include/  -I../../extern/include/  ...
        -lboost_thread -lboost_system -lstdc++...
        -outdir build ...
        src/simulink_get_data.cpp ...
        ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
        ../../src/definitions/constants.cpp ../../src/config/control_message_decoder.cpp ...
        ../../src/config/control_messages.cpp ../../src/config/control_message_encoder.cpp ...
        ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
        ../../extern/lib/ticpp/linux/libticpp_64.a

  end
    
    
%   mex -v -cxx -O -DTIXML_USE_TICPP -outdir build ...
%     -I../../include/  -I../../extern/include/  ...
%     -lboost_thread -lboost_system -lstdc++...
%       src/mex_get_config.cpp    ...
%       ../../tmp/data_packet.o ../../tmp/raw_mem.o ...
%       ../../tmp/constants.o ../../tmp/control_message_encoder.o ...
%       ../../tmp/control_messages.o ../../tmp/control_message_decoder.o ...
%       ../../tmp/ssclient.o ../../tmp/ssclientimpl.o ...
%       ../../extern/lib/ticpp/linux/libticpp.a


%  mex -v -cxx -O -DTIXML_USE_TICPP -outdir build ...
%    -I../../include  -I../../extern/include/  ...
%    -lboost_thread -lboost_system -lstdc++...
%      src/simulink_get_data.cpp ...
%      ../../tmp/data_packet.o ../../tmp/raw_mem.o ...
%      ../../tmp/constants.o ../../tmp/control_message_encoder.o ...
%      ../../tmp/control_messages.o ../../tmp/control_message_decoder.o ...
%      ../../tmp/ssclient.o ../../tmp/ssclientimpl.o ...
%      ../../extern/lib/ticpp/linux/libticpp.a


%  mex -v -cxx -g -DTIXML_USE_TICPP -outdir build ...
%      -I../../include  -I../../extern/include/  ...
%      src/simulink_get_data.cpp

%   mex -v -cxx -O -DTIXML_USE_TICPP -outdir build ...
%     -I../../include  -I../../extern/include/  ...
%     -lboost_system ...
%       src/simulink_get_data.cpp ...
%     ../../lib/libssclient.a  ../../extern/lib/ticpp/linux/libticpp.a

        %-lboost_thread -lboost_system -lstdc++...

else

  mex -v -O -DTIXML_USE_TICPP -DWIN32 -D_WIN32_WINNT=0x0501 ...
    -IC:\Programme\boost\boost_1_42  -I../../include/  -I../../extern/include/  ...
    -L../lib_ticpp -LC:\Programme\boost\boost_1_42\lib ...
    -outdir build ...
      src/mex_get_config.cpp    ...
      ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
      ../../src/definitions/constants.cpp ../../src/config/control_message_encoder.cpp ...
      ../../src/config/control_messages.cpp ../../src/config/control_message_decoder.cpp ...
      ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
      ../../extern/include/ticpp/tinyxmlparser.cpp ../../extern/include/ticpp/tinyxmlerror.cpp ...
      ../../extern/include/ticpp/tinystr.cpp ../../extern/include/ticpp/tinyxml.cpp ../../extern/include/ticpp/ticpp.cpp ...
      -llibboost_system-vc90-mt-1_42 -llibboost_date_time-vc90-mt-1_42 -llibboost_regex-vc90-mt-1_42 -llibboost_thread-vc90-mt-1_42


  mex -v -O -DTIXML_USE_TICPP -DWIN32 -D_WIN32_WINNT=0x0501 ...
    -IC:\Programme\boost\boost_1_42  -I../../include  -I../../extern/include/  ...
    -LC:\Programme\boost\boost_1_42\lib  ...
    -outdir build ...
      src/simulink_get_data.cpp ...
      ../../src/datapacket/data_packet.cpp ../../src/datapacket/raw_mem.cpp ...
      ../../src/definitions/constants.cpp ../../src/config/control_message_decoder.cpp ...
      ../../src/config/control_messages.cpp ../../src/config/control_message_encoder.cpp ...
      ../../src/signalserver-client/ssclient.cpp ../../src/signalserver-client/ssclientimpl.cpp ...
      ../../extern/include/ticpp/tinyxmlparser.cpp ../../extern/include/ticpp/tinyxmlerror.cpp ...
      ../../extern/include/ticpp/tinystr.cpp ../../extern/include/ticpp/tinyxml.cpp ../../extern/include/ticpp/ticpp.cpp ...
      ../../extern/include/LptTools/LptTools.cpp ...
      -llibboost_system-vc90-mt-1_42 -llibboost_date_time-vc90-mt-1_42 -llibboost_regex-vc90-mt-1_42 -llibboost_thread-vc90-mt-1_42

end



%   mex -cxx -O -DWall -DTIXML_USE_TICPP -lboost_thread -lboost_system ...
%     mex_get_config.cpp    ../data_packet.o ../raw_mem.o ../constants.o ../ssclient/ssclientimpl.o ...
%     ../control_message_encoder.o ../control_message_decoder.o ../ssclient/ssclient.o ...
%     ../control_messages.o ../LptToolsLinux.o ../lib_ticpp/libticpp.a
%
%   mex -cxx -O -DWall -DTIXML_USE_TICPP -lboost_thread -lboost_system simulink_get_data.cpp ...
%     ../data_packet.o ../raw_mem.o ../constants.o ../ssclient/ssclientimpl.o ...
%     ../control_message_decoder.o ../control_message_encoder.o ../ssclient/ssclient.o ...
%     ../control_messages.o ../LptToolsLinux.o ../lib_ticpp/libticpp.a

